spring:
  application:
    name: morp-eureka-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${PORT:2011}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: https://morp-eureka-service.herokuapp.com:${server.port}/eureka
      non-secure-port: ${PORT:2011}
      secure-port: 443

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #milliseconds
        readTimeout: 10000